org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2]
forge_version=47.1.0
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=xannosz_airship
mod_name=Poor man's airship mod
mod_license=MIT
mod_version=1.20-1.0
mod_group_id=xannosz.airship
mod_link=https://www.curseforge.com/minecraft/mc-mods/poor-mans-airship-mod
mod_authors=Xannosz
mod_description=Do you have a weak server, but want to travel the world with all your stuff? \
  Do you have a potato computer, but want to build a working flying city? Finally, there's a mod for you, a \
  server-friendly airship mod for cheap computers!